### ISSUE TITLE
The lib is not compiled

### ISSUE THREAD

**Issue by GooseDB** [tttapa/Control-Surface#26]
src/MIDI_Inputs/MCU/VU.hpp:14:31: error: macro "max" requires 2 arguments, but only 1 given
     IVU(uint8_t max) : max(max) {}

https://github.com/tttapa/Control-Surface/blob/master/src/MIDI_Inputs/MCU/VU.hpp#L14

I can't get what this code does, and can't fix it myself. Can you fix?

**Comment by tttapa** [comment]
What board are you using?

The reason is that the Arduino core for your particular board defines a global max macro, which is bad practice because it gives rise to name collisions.

**Comment by tttapa** [comment]
I created a new branch with a temporary fix. Does it compile now, or are there other errors?

**Comment by GooseDB** [comment]
Yes. You are right. Thank you.

**Comment by GooseDB** [comment]
Yes. It works. Thank you.
